In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r'C:\Users\ashmit\Downloads\USDINR_DataFile.csv')

In [14]:
data.isna().sum()

INR_per_USD                              0
CAD_Ind_Q                                0
GDP_Ind_Q                                0
GDP_Ind_per_Q_2004_2005                  0
Inflation_Ind_M                          0
MIBOR                                    0
LIBOR                                    0
FDI_Ind_14169_M                          0
RBI_Repo_Rate_Date                       0
Trade_Deficit_Ind_M                      0
Fiscal_Deficit_Ind_Y                     0
NIFTY_PE_Ind_D                           0
Brent_D                                  0
US_GDP_perc_Q                            0
US_NFP_M                                 0
US_Unemp_Q                               0
Strength_USD_D                           0
Inflation_USA_percen_m                   0
FEDFUNDS_USA_m                           0
US_Net_Inter_Invest_Position_USD_mn_q    0
FDI_US_USD_mn_q                          0
Trade_Deficit_USA_USD_mn_m               0
month                                    0
year                                     0
date                                     0
dtype: int64

In [4]:
data.drop('Forieg_equit_inv_Ind_D', axis=1, inplace=True)
data.drop('Forieg_Debt_inv__Ind_D', axis=1, inplace=True)
data.drop('Tourism_IND_USD_mn_Yr', axis=1, inplace=True)
data.drop('Tourism_USA_USD_mn_Yr', axis=1, inplace=True)
data

,Date,INR_per_USD,CAD_Ind_Q,GDP_Ind_Q,GDP_Ind_per_Q_2004_2005,Inflation_Ind_M,MIBOR,LIBOR,FDI_Ind_14169_M,RBI_Repo_Rate_Date,...,US_NFP_M,US_Unemp_Q,Strength_USD_D,Inflation_USA_percen_m,FEDFUNDS_USA_m,US_Net_Inter_Invest_Position_USD_mn_q,FDI_US_USD_mn_q,Discount_rate_USA_perc_m,Trade_Deficit_USA_USD_mn_m,Fiscal_Deficit_USA_per_Y
0,01-01-2012,53.3062,-4.44,5.1,5.8,6.26,8.010000,0.582250,871,8.5,...,348,8.27,80.4420,2.925217,0.08,-4547907,2993642,0.75,-50983,-6.73
1,02-01-2012,53.3062,-4.44,5.1,5.8,6.26,8.010000,0.582250,871,8.5,...,348,8.27,80.2800,2.925217,0.08,-4547907,2993642,0.75,-50983,-6.73
2,03-01-2012,53.2250,-4.44,5.1,5.8,6.26,7.890000,0.582500,871,8.5,...,348,8.27,79.6110,2.925217,0.08,-4547907,2993642,0.75,-50983,-6.73
3,04-01-2012,52.9750,-4.44,5.1,5.8,6.26,7.650000,0.582500,871,8.5,...,348,8.27,80.1290,2.925217,0.08,-4547907,2993642,0.75,-50983,-6.73
4,05-01-2012,52.9850,-4.44,5.1,5.8,6.26,7.590000,0.582500,871,8.5,...,348,8.27,80.9360,2.925217,0.08,-4547907,2993642,0.75,-50983,-6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,27-12-2017,64.1525,-1.53,7.2,4.9,5.21,5.780000,1.693390,4322,6.0,...,175,4.10,93.0250,2.109082,1.30,-7845809,4526282,NaN,-53908,NaN
2188,28-12-2017,64.0800,-1.53,7.2,4.9,5.21,6.440000,1.694650,4322,6.0,...,175,4.10,92.6020,2.109082,1.30,-7845809,4526282,NaN,-53908,NaN
2189,29-12-2017,63.8713,-1.53,7.2,4.9,5.21,6.540000,1.694280,4322,6.0,...,175,4.10,92.1240,2.109082,1.30,-7845809,4526282,NaN,-53908,NaN
2190,30-12-2017,63.8713,-1.53,7.2,4.9,5.21,6.079088,1.689068,4322,6.0,...,175,4.10,92.8550,2.109082,1.30,-7845809,4526282,NaN,-53908,NaN
2191,31-12-2017,63.8713,-1.53,7.2,4.9,5.21,6.129818,1.692847,4322,6.0,...,175,4.10,92.7726,2.109082,1.30,-7845809,4526282,NaN,-53908,NaN

In [5]:
data.drop('Discount_rate_USA_perc_m', axis=1, inplace=True)
data.drop('Fiscal_Deficit_USA_per_Y', axis=1, inplace=True)

In [6]:
data['Date']=pd.to_datetime(data['Date'])

In [7]:
data['month']=data['Date'].dt.month
data['year']=data['Date'].dt.year
data['date']=data['Date'].dt.day
data.drop('Date', axis=1, inplace=True)

In [8]:
for column in data.columns:
    if(column!='INR_per_USD'):
        data[column]=data[column]/data[column].max()

In [9]:
#gets a random 80% of the entire set
X_train = data.sample(frac=0.9, random_state=1)
#gets the left out portion of the dataset
X_test = data.loc[~data.index.isin(X_train.index)]
data['INR_per_USD']

0       53.3062
1       53.3062
2       53.2250
3       52.9750
4       52.9850
         ...
2187    64.1525
2188    64.0800
2189    63.8713
2190    63.8713
2191    63.8713
Name: INR_per_USD, Length: 2192, dtype: float64

In [10]:
y_train=X_train['INR_per_USD']
y_test=X_test['INR_per_USD']

In [11]:
X_train.drop('INR_per_USD', axis=1, inplace=True)
X_test.drop('INR_per_USD', axis=1, inplace=True)

C:\Users\ashmit\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [12]:
import numpy as np
from sklearn import metrics, linear_model

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, y_train)

predictions=regr.predict(X_test)

print("############### Predictions #################")
#print(predictions)
print("#############################################")

print("MAE = {0}".format(metrics.mean_absolute_error(y_test,predictions)))

print("MSE = {0}".format(metrics.mean_squared_error(y_test,predictions)))

############### Predictions #################
#############################################
MAE = 0.7179028799222098
MSE = 0.9478753232399553

In [13]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split

model=MLPRegressor(random_state=2, max_iter=5000, hidden_layer_sizes=(65), activation='tanh', learning_rate='invscaling')
regr = model.fit(X_train, y_train)
predictions=regr.predict(X_test)
print("MAE = {0}".format(metrics.mean_absolute_error(y_test,predictions)))

print("MSE = {0}".format(metrics.mean_squared_error(y_test,predictions)))

MAE = 0.41689302919450466
MSE = 0.3339230949836171